repos:
  - repo: local
    hooks:
      - id: packer_fmt
        name: Packer Format
        entry: packer fmt
        language: system
        pass_filenames: false
        args:
          - '.'
  - repo: local
    hooks:
      - id: packer_validate
        name: Packer Validate
        entry: packer validate
        language: system
        pass_filenames: false
        args: 
          - '.'